# IMPORTING THE LIBRARIES

In [0]:
# Importing pandas module
import pandas as pd
# Importing numpy module
import numpy as np

# READING THE DATASET FILE

In [0]:
# Reading the csv file
data = 'Loan_Transactions.csv'
df = pd.read_csv(data, encoding= 'latin1')

In [0]:
data1 = 'Guarantee_Utilization_and_Claims.csv'
df1 = pd.read_csv(data1, encoding='latin1')

In [0]:
# Showing the first five rows of the first dataset 
df.head()

                       Guarantee Number  ...  Longitude
0  099-DCA-09-006A (Asociacion Arariwa)  ... -71.978056
1      099-DCA-09-006B (Pro Mujer Peru)  ... -70.000000
2          099-DCA-09-006C (ProEmpresa)  ... -76.833333
3      099-DCA-09-006D (Pro Mujer Peru)  ...        NaN
4               099-DCA-09-006F (COCLA)  ... -71.978056

[5 rows x 18 columns]

In [0]:
# Showing the first five rows of the second dataset 
df1.head()

   Fiscal Year          Guarantee Number  ... Total Claims Pending Recoveries
0         1999                 49299G001  ...                    0        0.0
1         1999           674-A99-DCA-001  ...                    0        0.0
2         1999               674A99DCA02  ...                    0        0.0
3         1999          674A99DCA02 (PG)  ...                    0        0.0
4         2000  5200425DCA01(Terminated)  ...                    0        0.0

[5 rows x 22 columns]

In [0]:
# Merging the datasets
df_merged = pd.concat([df,df1], ignore_index=True, sort  =True)
df_merged
frames = [df,df1]
df_keys = pd.concat(frames, keys=['FIRST DF1', 'SECOND DF2'])
 
df_keys

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.

                Amount (USD)  ... USAID Guarantee Percentage
FIRST DF1  0    9.801444e+05  ...                        NaN
           1    1.960289e+06  ...                        NaN
           2    2.007491e+06  ...                        NaN
           3    1.030888e+06  ...                        NaN
           4    1.780000e+06  ...                        NaN
...                      ...  ...                        ...
SECOND DF2 611           NaN  ...                       54.0
           612           NaN  ...                       50.0
           613           NaN  ...                       50.0
           614           NaN  ...                       50.0
           615           NaN  ...                       30.0

[187161 rows x 39 columns]

In [0]:
df_merged.head()

   Amount (USD)  ... USAID Guarantee Percentage
0  9.801444e+05  ...                        NaN
1  1.960289e+06  ...                        NaN
2  2.007491e+06  ...                        NaN
3  1.030888e+06  ...                        NaN
4  1.780000e+06  ...                        NaN

[5 rows x 39 columns]

# EXPLORING THE DATASET

In [0]:
# Checking the number of columns
df_merged.columns

Index(['Amount (USD)', 'Business Sector', 'Business Size', 'City/Town',
       'Country', 'Credit Agreement Type', 'Cumulative Loans',
       'Cumulative Utilization', 'Cumulative Utilization Percent',
       'Currency Name', 'Disbursement Date',
       'Effective Maximum Cumulative Disbursements', 'End Date',
       'Final Date for Placing Loans under Coverage', 'Fiscal Year',
       'Guarantee Country Name', 'Guarantee End Date', 'Guarantee Number',
       'Guarantee Percentage', 'Guarantee Start Date',
       'Is First Time Borrower?', 'Is Woman Owned?', 'Latitude', 'Longitude',
       'Partner Name', 'Primary Target Sector Code',
       'Primary Target Segment Code', 'Recoveries', 'Region Name',
       'Secondary Target Sector Codes', 'Secondary Target Segment Codes',
       'State/Province/Region Code', 'State/Province/Region Country Name',
       'State/Province/Region Name', 'Status', 'Total Claims Paid',
       'Total Claims Pending', 'Transaction Report ID',
       'USAID Guarantee Percentage'],
      dtype='object')

In [0]:
# Checking the number of rows
df_merged.index

RangeIndex(start=0, stop=187161, step=1)

In [0]:
# Checking the number of rows and columns
df_merged.shape

(187161, 39)

In [0]:
# Getting the description of the dataset
df_merged.describe

<bound method NDFrame.describe of         Amount (USD)  ... USAID Guarantee Percentage
0       9.801444e+05  ...                        NaN
1       1.960289e+06  ...                        NaN
2       2.007491e+06  ...                        NaN
3       1.030888e+06  ...                        NaN
4       1.780000e+06  ...                        NaN
...              ...  ...                        ...
187156           NaN  ...                       54.0
187157           NaN  ...                       50.0
187158           NaN  ...                       50.0
187159           NaN  ...                       50.0
187160           NaN  ...                       30.0

[187161 rows x 39 columns]>

In [0]:
# Getting the information about the dataset
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187161 entries, 0 to 187160
Data columns (total 39 columns):
Amount (USD)                                   186545 non-null float64
Business Sector                                178564 non-null object
Business Size                                  39238 non-null object
City/Town                                      146253 non-null object
Country                                        616 non-null object
Credit Agreement Type                          616 non-null object
Cumulative Loans                               571 non-null float64
Cumulative Utilization                         571 non-null float64
Cumulative Utilization Percent                 571 non-null float64
Currency Name                                  186545 non-null object
Disbursement Date                              186545 non-null object
Effective Maximum Cumulative Disbursements     616 non-null float64
End Date                                       186545 non-null object
Final Date for Placing Loans under Coverage    616 non-null object
Fiscal Year                                    616 non-null float64
Guarantee Country Name                         186545 non-null object
Guarantee End Date                             616 non-null object
Guarantee Number                               187161 non-null object
Guarantee Percentage                           616 non-null float64
Guarantee Start Date                           616 non-null object
Is First Time Borrower?                        186545 non-null float64
Is Woman Owned?                                186545 non-null float64
Latitude                                       106799 non-null float64
Longitude                                      106799 non-null float64
Partner Name                                   616 non-null object
Primary Target Sector Code                     616 non-null object
Primary Target Segment Code                    616 non-null object
Recoveries                                     616 non-null float64
Region Name                                    134854 non-null object
Secondary Target Sector Codes                  108 non-null object
Secondary Target Segment Codes                 162 non-null object
State/Province/Region Code                     134854 non-null object
State/Province/Region Country Name             134854 non-null object
State/Province/Region Name                     134854 non-null object
Status                                         616 non-null object
Total Claims Paid                              616 non-null float64
Total Claims Pending                           616 non-null float64
Transaction Report ID                          186545 non-null float64
USAID Guarantee Percentage                     616 non-null float64
dtypes: float64(16), object(23)
memory usage: 55.7+ MB

# DATA CLEANING

# Validity

In [0]:
# Deleting unnecesarry data
df_merged.drop('Country', axis=1, inplace=True)

In [0]:
df_merged.drop('Status', axis=1, inplace=True)

# Accuracy

In [0]:
# changing the format of Disbursement Date and End Date
df_merged['Disbursement Date'] = pd.to_datetime(df_merged['Disbursement Date'])
df_merged['End Date'] = pd.to_datetime(df_merged['End Date'])

In [0]:
def check(row):
  if row['Disbursement Date'] < row['End Date']:
    return True
  else:
    return False

In [0]:
df_merged['verifier'] = df_merged.apply(lambda row:check(row), axis=1)
df_merged.head()

   Amount (USD) Business Sector  ... USAID Guarantee Percentage verifier
0  9.801444e+05             NaN  ...                        NaN     True
1  1.960289e+06             NaN  ...                        NaN     True
2  2.007491e+06             NaN  ...                        NaN     True
3  1.030888e+06             NaN  ...                        NaN     True
4  1.780000e+06             NaN  ...                        NaN     True

[5 rows x 38 columns]

# Completeness

In [0]:
# Checking for null values
df_merged.isnull().any().any()

True

In [0]:
df_merged.isnull().sum().sum()

4117760

In [0]:
df_merged.isnull().sum()

Amount (USD)                                      616
Business Sector                                  8597
Business Size                                  147923
City/Town                                       40908
Credit Agreement Type                          186545
Cumulative Loans                               186590
Cumulative Utilization                         186590
Cumulative Utilization Percent                 186590
Currency Name                                     616
Disbursement Date                                 616
Effective Maximum Cumulative Disbursements     186545
End Date                                          616
Final Date for Placing Loans under Coverage    186545
Fiscal Year                                    186545
Guarantee Country Name                            616
Guarantee End Date                             186545
Guarantee Number                                    0
Guarantee Percentage                           186545
Guarantee Start Date                           186545
Is First Time Borrower?                           616
Is Woman Owned?                                   616
Latitude                                        80362
Longitude                                       80362
Partner Name                                   186545
Primary Target Sector Code                     186545
Primary Target Segment Code                    186545
Recoveries                                     186545
Region Name                                     52307
Secondary Target Sector Codes                  187053
Secondary Target Segment Codes                 186999
State/Province/Region Code                      52307
State/Province/Region Country Name              52307
State/Province/Region Name                      52307
Total Claims Paid                              186545
Total Claims Pending                           186545
Transaction Report ID                             616
USAID Guarantee Percentage                     186545
verifier                                            0
dtype: int64

In [0]:
# Fill the null values with 0
df_merged.fillna(0)

        Amount (USD) Business Sector  ... USAID Guarantee Percentage verifier
0       9.801444e+05               0  ...                        0.0     True
1       1.960289e+06               0  ...                        0.0     True
2       2.007491e+06               0  ...                        0.0     True
3       1.030888e+06               0  ...                        0.0     True
4       1.780000e+06               0  ...                        0.0     True
...              ...             ...  ...                        ...      ...
187156  0.000000e+00               0  ...                       54.0    False
187157  0.000000e+00               0  ...                       50.0    False
187158  0.000000e+00               0  ...                       50.0    False
187159  0.000000e+00               0  ...                       50.0    False
187160  0.000000e+00               0  ...                       30.0    False

[187161 rows x 38 columns]

# Consistency

In [0]:
# Checking for duplicates
df_merged.duplicated().any().any()

False

# Uniformity

In [0]:
# I have changed two column in accuracy to datetime format

In [0]:
# Changing all the columns to lowercase
df_merged.columns.str.lower()

Index(['amount (usd)', 'business sector', 'business size', 'city/town',
       'credit agreement type', 'cumulative loans', 'cumulative utilization',
       'cumulative utilization percent', 'currency name', 'disbursement date',
       'effective maximum cumulative disbursements', 'end date',
       'final date for placing loans under coverage', 'fiscal year',
       'guarantee country name', 'guarantee end date', 'guarantee number',
       'guarantee percentage', 'guarantee start date',
       'is first time borrower?', 'is woman owned?', 'latitude', 'longitude',
       'partner name', 'primary target sector code',
       'primary target segment code', 'recoveries', 'region name',
       'secondary target sector codes', 'secondary target segment codes',
       'state/province/region code', 'state/province/region country name',
       'state/province/region name', 'total claims paid',
       'total claims pending', 'transaction report id',
       'usaid guarantee percentage', 'verifier'],
      dtype='object')

# Exporting the clean dataset

In [0]:
df_merged.to_csv('CleanTings.csv')

In [0]:
from google.colab import files
files.download("CleanTings.csv")